# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 353)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(200, 290, 441, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.formGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.formGroupBox.setGeometry(QtCore.QRect(10, 10, 171, 301))
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.s1__lb_1)
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s1__box_1)
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.s1__lb_2)
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_2.setObjectName("s1__box_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s1__box_2)
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.s1__lb_3)
        self.s1__box_3 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.s1__box_3)
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.s1__lb_4)
        self.s1__box_4 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.s1__box_4)
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.s1__lb_5)
        self.s1__box_5 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.s1__box_5)
        self.open_button = QtWidgets.QPushButton(self.formGroupBox)
        self.open_button.setObjectName("open_button")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.open_button)
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.s1__lb_6)
        self.s1__box_6 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.s1__box_6)
        self.state_label = QtWidgets.QLabel(self.formGroupBox)
        self.state_label.setText("")
        self.state_label.setTextFormat(QtCore.Qt.AutoText)
        self.state_label.setScaledContents(True)
        self.state_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label.setObjectName("state_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.state_label)
        self.close_button = QtWidgets.QPushButton(self.formGroupBox)
        self.close_button.setObjectName("close_button")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.close_button)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(190, 10, 441, 271))
        self.groupBox.setObjectName("groupBox")
        self.s3__send_text = QtWidgets.QTextEdit(self.groupBox)
        self.s3__send_text.setGeometry(QtCore.QRect(10, 40, 421, 51))
        self.s3__send_text.setObjectName("s3__send_text")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 111, 16))
        self.label_3.setObjectName("label_3")
        self.reverseLEDs = QtWidgets.QCheckBox(self.groupBox)
        self.reverseLEDs.setEnabled(True)
        self.reverseLEDs.setGeometry(QtCore.QRect(290, 190, 91, 21))
        self.reverseLEDs.setObjectName("reverseLEDs")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 151, 16))
        self.label_2.setObjectName("label_2")
        self.sliderSpeed = QtWidgets.QSlider(self.groupBox)
        self.sliderSpeed.setEnabled(True)
        self.sliderSpeed.setGeometry(QtCore.QRect(40, 120, 161, 21))
        self.sliderSpeed.setOrientation(QtCore.Qt.Horizontal)
        self.sliderSpeed.setObjectName("sliderSpeed")
        self.sliderBrightness = QtWidgets.QSlider(self.groupBox)
        self.sliderBrightness.setGeometry(QtCore.QRect(40, 170, 160, 22))
        self.sliderBrightness.setOrientation(QtCore.Qt.Horizontal)
        self.sliderBrightness.setObjectName("sliderBrightness")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(270, 100, 161, 16))
        self.label_6.setObjectName("label_6")
        self.s3__send_button = QtWidgets.QPushButton(self.groupBox)
        self.s3__send_button.setEnabled(False)
        self.s3__send_button.setGeometry(QtCore.QRect(260, 220, 161, 31))
        self.s3__send_button.setObjectName("s3__send_button")
        self.inputAnimation = QtWidgets.QComboBox(self.groupBox)
        self.inputAnimation.setGeometry(QtCore.QRect(340, 120, 81, 22))
        self.inputAnimation.setObjectName("inputAnimation")
        self.inputAnimation.addItem("")
        self.inputAnimation.addItem("")
        self.inputAnimation.addItem("")
        self.inputAnimation.addItem("")
        self.outputAnimation = QtWidgets.QComboBox(self.groupBox)
        self.outputAnimation.setGeometry(QtCore.QRect(340, 150, 81, 22))
        self.outputAnimation.setObjectName("outputAnimation")
        self.outputAnimation.addItem("")
        self.outputAnimation.addItem("")
        self.outputAnimation.addItem("")
        self.outputAnimation.addItem("")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(270, 120, 47, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(270, 150, 47, 13))
        self.label_5.setObjectName("label_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 170, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(210, 170, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB Demi")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 200, 141, 16))
        self.label_11.setObjectName("label_11")
        self.sliderTimeScreen = QtWidgets.QSlider(self.groupBox)
        self.sliderTimeScreen.setGeometry(QtCore.QRect(40, 220, 160, 22))
        self.sliderTimeScreen.setOrientation(QtCore.Qt.Horizontal)
        self.sliderTimeScreen.setObjectName("sliderTimeScreen")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(20, 220, 16, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(210, 220, 16, 16))
        self.label_13.setObjectName("label_13")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 21, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(210, 120, 47, 13))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.formGroupBox.setTitle(_translate("MainWindow", "Configuración del puerto serie"))
        self.s1__lb_1.setText(_translate("MainWindow", "Detección"))
        self.s1__box_1.setText(_translate("MainWindow", "Detectar"))
        self.s1__lb_2.setText(_translate("MainWindow", "Selección"))
        self.s1__lb_3.setText(_translate("MainWindow", "Velocidad:"))
        self.s1__box_3.setItemText(0, _translate("MainWindow", "115200"))
        self.s1__box_3.setItemText(1, _translate("MainWindow", "2400"))
        self.s1__box_3.setItemText(2, _translate("MainWindow", "4800"))
        self.s1__box_3.setItemText(3, _translate("MainWindow", "9600"))
        self.s1__box_3.setItemText(4, _translate("MainWindow", "14400"))
        self.s1__box_3.setItemText(5, _translate("MainWindow", "19200"))
        self.s1__box_3.setItemText(6, _translate("MainWindow", "38400"))
        self.s1__box_3.setItemText(7, _translate("MainWindow", "57600"))
        self.s1__box_3.setItemText(8, _translate("MainWindow", "76800"))
        self.s1__box_3.setItemText(9, _translate("MainWindow", "12800"))
        self.s1__box_3.setItemText(10, _translate("MainWindow", "230400"))
        self.s1__box_3.setItemText(11, _translate("MainWindow", "460800"))
        self.s1__lb_4.setText(_translate("MainWindow", "Bits de datos:"))
        self.s1__box_4.setItemText(0, _translate("MainWindow", "8"))
        self.s1__box_4.setItemText(1, _translate("MainWindow", "7"))
        self.s1__box_4.setItemText(2, _translate("MainWindow", "6"))
        self.s1__box_4.setItemText(3, _translate("MainWindow", "5"))
        self.s1__lb_5.setText(_translate("MainWindow", "Díg de control:"))
        self.s1__box_5.setItemText(0, _translate("MainWindow", "N"))
        self.open_button.setText(_translate("MainWindow", "Abrir puerto serie"))
        self.s1__lb_6.setText(_translate("MainWindow", "Bit de parada:"))
        self.s1__box_6.setItemText(0, _translate("MainWindow", "1"))
        self.close_button.setText(_translate("MainWindow", "Cerrar puerto serie"))
        self.groupBox.setTitle(_translate("MainWindow", "Zona de envio"))
        self.label_3.setText(_translate("MainWindow", "Brillo de LED´s"))
        self.reverseLEDs.setText(_translate("MainWindow", "Invertir LED´s"))
        self.label.setText(_translate("MainWindow", "Texto a enviar"))
        self.label_2.setText(_translate("MainWindow", "Velocidad de desplazamineto"))
        self.label_6.setText(_translate("MainWindow", "Seleccione dirección de animación"))
        self.s3__send_button.setText(_translate("MainWindow", "Enviar"))
        self.inputAnimation.setItemText(0, _translate("MainWindow", "ARRIBA"))
        self.inputAnimation.setItemText(1, _translate("MainWindow", "ABAJO"))
        self.inputAnimation.setItemText(2, _translate("MainWindow", "IZQUIERDA"))
        self.inputAnimation.setItemText(3, _translate("MainWindow", "DERECHA"))
        self.outputAnimation.setItemText(0, _translate("MainWindow", "ARRIBA"))
        self.outputAnimation.setItemText(1, _translate("MainWindow", "ABAJO"))
        self.outputAnimation.setItemText(2, _translate("MainWindow", "IZQUIERDA"))
        self.outputAnimation.setItemText(3, _translate("MainWindow", "DERECHA"))
        self.label_4.setText(_translate("MainWindow", "Entrada:"))
        self.label_5.setText(_translate("MainWindow", "Salida:"))
        self.label_9.setText(_translate("MainWindow", "-"))
        self.label_10.setText(_translate("MainWindow", "+"))
        self.label_11.setText(_translate("MainWindow", "Tiempo de espera en pantalla"))
        self.label_12.setText(_translate("MainWindow", "0 s"))
        self.label_13.setText(_translate("MainWindow", "5 s"))
        self.label_7.setText(_translate("MainWindow", "1 ms"))
        self.label_8.setText(_translate("MainWindow", "100 ms"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

